version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: store-api-postgres
    environment:
      POSTGRES_DB: storedb
      POSTGRES_USER: storeuser
      POSTGRES_PASSWORD: storepassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - store-network

  minio:
    image: minio/minio
    container_name: store-api-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - store-network

networks:
  store-network:
    driver: bridge

volumes:
  postgres_data:
  minio_data: